# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decision', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='decision',
            name='label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
