# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-08 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0002_auto_20170408_1928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='number_of_users',
            new_name='number_of_external_users',
        ),
        migrations.AddField(
            model_name='event',
            name='number_of_internal_users',
            field=models.IntegerField(default=0),
        ),
    ]
