# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0004_event_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='requires_credentials',
            field=models.BooleanField(default=False),
        ),
    ]
