# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0005_event_requires_credentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='internal_only',
            field=models.BooleanField(default=False),
        ),
    ]
